import turtle
print("AUDİ SİMGESİ ÇİZİLMEYE BAŞLAMIŞTIR...")
a = turtle.Turtle()
a.shape("turtle")
a.color("blue","orange")
a.pensize (7)
a.speed(1.5)
a.circle(100)
a.fd(120)
a.speed(2.5)
a.circle(100)
a.fd(120)
a.speed(10)
a.circle(100)
a.fd(120)
a.circle(100)
print("AUDİ SİMGESİ ÇİZİLMİŞTİR.")